[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://p7-kasa-openclassrooms.netlify.app"
    Access-Control-Allow-Methods = "GET"
    Access-Control-Allow-Headers = "Content-Type"
